// AKME Immigrations & Education - Core Configuration

export const SITE_CONFIG = {
  name: "AKME Immigrations",
  legalName: "AKME Immigrations & Education",
  tagline: "Transforming Dreams into Destination",
  description: "Official portal of AKME Immigrations & Education, Patiala. Expert guidance for Study Visas, Immigration / PR, Visitor Visas, IELTS, PTE, and Foreign Language Preparation.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://akmeimmigrations.com",
  phone: "+91 98155-12980",
  phoneRaw: "+919815512980",
  phoneDisplay: "+91 98155 12980",
  email: "akme.help@gmail.com",
  whatsappNumber: "919815512980",
  whatsappMessage: "Hello AKME Immigrations, I would like to know more about your visa and study abroad services.",
  address: {
    line1: "SCO 37 & 38, Near Vardhman Hospital",
    line2: "Urban Estate Phase II, Rajpura Road",
    city: "Patiala",
    state: "Punjab",
    pincode: "147002",
    country: "India",
    full: "SCO 37 & 38, near Vardhman Hospital, Urban Estate Phase II, Rajpura Road, Patiala, Punjab 147002, India",
    mapsUrl: "https://maps.google.com/?q=SCO+37+and+38+near+Vardhman+Hospital+Urban+Estate+Patiala+Punjab+147002",
  },
  hours: {
    days: "Monday - Saturday",
    time: "9:30 AM - 6:30 PM IST",
    sunday: "Closed (Prior appointment only)",
  },
  social: {
    facebook: "https://www.facebook.com/akmeimmigrations/",
    instagram: "https://www.instagram.com/akme_immigrations/",
    youtube: "https://www.youtube.com/@akmeimmigrations",
    linkedin: "https://www.linkedin.com/company/akme-immigrations",
  },
  disclaimer: "Visa and immigration outcomes depend on individual circumstances, documentation authenticity, and the statutory discretion of the respective government authorities. Information provided on this website is for general guidance purposes and does not constitute formal legal counsel. AKME Immigrations does not collect or process university tuition fees; students pay directly to certified institutions.",
};

export const SERVICES_LIST = [
  {
    slug: "study-visa",
    title: "Study Visa",
    shortDesc: "Complete admissions and student visa processing for top globally ranked institutions.",
    icon: "GraduationCap",
    badge: "Most Popular",
  },
  {
    slug: "immigration",
    title: "Immigration & PR",
    shortDesc: "Strategic legal pathway planning for skilled permanent residency and Express Entry.",
    icon: "FileCheck2",
    badge: "Expert Advisory",
  },
  {
    slug: "visitor-visa",
    title: "Visitor & Tourist Visa",
    shortDesc: "Comprehensive documentation and statement preparation for hassle-free tourist travel.",
    icon: "Plane",
    badge: "Quick Process",
  },
  {
    slug: "business-immigration",
    title: "Business & Investor Visa",
    shortDesc: "Investor programs, entrepreneur pathways, and international business relocation.",
    icon: "Briefcase",
    badge: "High Net Worth",
  },
  {
    slug: "ielts",
    title: "IELTS Coaching",
    shortDesc: "Certified IELTS Academic & General training with real exam practice and band guarantee modules.",
    icon: "BookOpen",
    badge: "In-House Training",
  },
  {
    slug: "pte",
    title: "PTE Academic Prep",
    shortDesc: "Computer-lab AI scoring practice, simulated sectional mocks, and targeted speaking clinics.",
    icon: "Languages",
    badge: "Lab Access",
  },
  {
    slug: "language-courses",
    title: "Foreign Languages (German / French)",
    shortDesc: "A1 to B2 level certified foreign language batches for European university admissions & PR points.",
    icon: "Award",
    badge: "Certified Faculty",
  },
];

export const COUNTRIES_LIST = [
  {
    slug: "canada",
    name: "Canada",
    code: "CA",
    headline: "Study & Settle in Canada",
    tagline: "PGWP work rights, world-class colleges, and structured permanent residency pathways.",
    intakes: "Fall (Sep), Winter (Jan), Spring (May)",
    avgTuition: "CAD $16,000 - $32,000 / year",
    popularPrograms: ["Computer Science", "Business & Project Mgmt", "Health Sciences", "Engineering"],
    postStudyWork: "Up to 3 Years Post-Graduation Work Permit (PGWP)",
  },
  {
    slug: "australia",
    name: "Australia",
    code: "AU",
    headline: "World-Class Education in Australia",
    tagline: "Group of Eight universities, post-study work visas, and high quality of life.",
    intakes: "Semester 1 (Feb/March), Semester 2 (July)",
    avgTuition: "AUD $22,000 - $44,000 / year",
    popularPrograms: ["Information Technology", "Nursing & Public Health", "Engineering", "Business"],
    postStudyWork: "2 to 4 Years Subclass 485 Temporary Graduate Visa",
  },
  {
    slug: "uk",
    name: "United Kingdom",
    code: "GB",
    headline: "Fast-Track Degrees in the UK",
    tagline: "1-year Master's programs, Russell Group universities, and the Graduate Route visa.",
    intakes: "September/October, January/February",
    avgTuition: "£13,000 - £26,000 / year",
    popularPrograms: ["MBA & Finance", "Data Science & AI", "Biomedical Science", "Law"],
    postStudyWork: "2 Years Graduate Route Post-Study Work Visa",
  },
  {
    slug: "usa",
    name: "United States",
    code: "US",
    headline: "Global Innovation & Degrees in the USA",
    tagline: "Top ranked research universities, STEM OPT extensions, and campus assistantships.",
    intakes: "Fall (August), Spring (January)",
    avgTuition: "$20,000 - $45,000 / year",
    popularPrograms: ["Computer & Data Engineering", "MBA", "Biotechnology", "Applied Physics"],
    postStudyWork: "1 Year OPT + 2 Year STEM Extension (Total up to 36 months)",
  },
  {
    slug: "germany",
    name: "Germany",
    code: "DE",
    headline: "Zero/Low Tuition Higher Education in Germany",
    tagline: "Public university low/no tuition tuition models, engineering excellence, and 18-month job seeker visa.",
    intakes: "Winter (Oct), Summer (April)",
    avgTuition: "€0 - €3,000 / semester (Semester contribution only in public universities)",
    popularPrograms: ["Mechanical & Automotive Eng", "Computer Science", "Renewable Energy", "Management"],
    postStudyWork: "18 Months Post-Study Job Search Permit",
  },
  {
    slug: "ireland",
    name: "Ireland",
    code: "IE",
    headline: "European Tech & Corporate Hub",
    tagline: "European headquarters of Google, Apple & Meta with 2-year third-level graduate scheme.",
    intakes: "Autumn (September), Spring (January)",
    avgTuition: "€11,000 - €25,000 / year",
    popularPrograms: ["Cloud Computing", "Pharmaceutical Sciences", "Financial Analytics", "Digital Marketing"],
    postStudyWork: "2 Years Third Level Graduate Scheme (Masters)",
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    code: "NZ",
    headline: "Safe, Welcoming, High-Quality Education",
    tagline: "Practical applied learning, scenic lifestyle, and post-study open work visas.",
    intakes: "February, July",
    avgTuition: "NZD $22,000 - $35,000 / year",
    popularPrograms: ["Hospitality & Tourism", "Agribusiness", "Information Systems", "Construction"],
    postStudyWork: "Up to 3 Years Post-Study Work Visa",
  },
];
