// AKME Immigrations & Education - Core Configuration

export const SITE_CONFIG = {
  name: "AKME Immigrations & Education",
  shortName: "AKME Immigrations",
  legalName: "AKME Immigrations & Education",
  tagline: "Patiala's Trusted Immigration & Education Institute",
  description: "Official portal of AKME Immigrations & Education, Patiala. Study Abroad, Immigration, Test Preparation (IELTS/PTE/CELPIP/CAEL/GRE/Duolingo) and Foreign Language Training (French/German/Spoken English) — Opposite Punjabi University, Patiala.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://akmeimmigrations.com",
  phone: "+91 98155-12980",
  phoneRaw: "+919815512980",
  phoneDisplay: "+91 98155 12980",
  email: "akme.help@gmail.com",
  whatsappNumber: "919815512980",
  whatsappMessage: "Hello AKME Immigrations & Education, I would like to schedule a free profile assessment for my study/visa plan.",
  address: {
    line1: "Opposite Punjabi University",
    line2: "Patiala",
    city: "Patiala",
    state: "Punjab",
    country: "India",
    landmark: "Opposite Punjabi University",
    full: "Opposite Punjabi University, Patiala, Punjab, India",
    display: "Opposite Punjabi University, Patiala",
    mapsUrl: "https://maps.google.com/?q=Punjabi+University+Patiala+Punjab",
  },
  hours: {
    days: "Monday - Saturday",
    time: "9:30 AM - 6:30 PM IST",
    sunday: "Closed (Prior appointment only)",
  },
  social: {
    facebook: "https://www.facebook.com/akmeimmigrations/",
    instagram: "https://www.instagram.com/akme_immigrations/",
    youtube: "https://www.youtube.com/@akmeimmigrations",
    linkedin: "https://www.linkedin.com/company/akme-immigrations",
  },
  disclaimer: "Visa and immigration outcomes depend on individual profile qualifications, authentic documentation, and the statutory discretion of the respective embassy or immigration authorities. Information provided on this website is for guidance purposes only and does not constitute a visa guarantee or formal legal counsel. AKME Immigrations & Education never collects or holds foreign university tuition fees; students remit tuition directly to designated foreign educational institutions.",
};

// 4 Primary Service Pillars for Section "What Can We Help You With?"
export const PRIMARY_SERVICE_PILLARS = [
  {
    title: "Study Abroad",
    description: "Choose the right country, university and course with expert admission and study visa guidance.",
    cta: "Explore Study Abroad",
    href: "/study-abroad",
    icon: "GraduationCap",
    badge: "Comprehensive Guidance",
  },
  {
    title: "Immigration",
    description: "Explore PR, PNP, visitor and immigration pathways for Canada, Australia and other destinations.",
    cta: "Explore Immigration",
    href: "/immigration",
    icon: "FileCheck2",
    badge: "Profile-Based Pathways",
  },
  {
    title: "Test Preparation",
    description: "Prepare confidently for IELTS, PTE, CELPIP, CAEL, GRE and Duolingo with structured coaching.",
    cta: "Explore Test Preparation",
    href: "/test-preparation",
    icon: "BookOpen",
    badge: "Computer Lab & Mocks",
  },
  {
    title: "Languages",
    description: "Build your language skills with French, German and Spoken English training.",
    cta: "Explore Languages",
    href: "/languages",
    icon: "Languages",
    badge: "A1 to B2 Batches",
  },
];

// Study Abroad Countries
export const STUDY_ABROAD_COUNTRIES = [
  {
    slug: "canada",
    name: "Canada",
    code: "CA",
    headline: "Study in Canada",
    tagline: "Post-Graduation Work Permit (PGWP) of up to 3 years and pathway to Canadian PR.",
    intakes: "Fall (September), Winter (January), Spring/Summer (May)",
    avgTuition: "CAD $16,000 - $32,000 / year",
    popularPrograms: ["Computer Science & Software Development", "Business & Project Management", "Health Sciences & Nursing", "Supply Chain & Logistics"],
    postStudyWork: "Up to 3 Years Post-Graduation Work Permit (PGWP)",
    flag: "🇨🇦",
  },
  {
    slug: "australia",
    name: "Australia",
    code: "AU",
    headline: "Study in Australia",
    tagline: "Top Group of Eight research institutions and Subclass 485 Temporary Graduate visas.",
    intakes: "Semester 1 (Feb/March), Semester 2 (July)",
    avgTuition: "AUD $22,000 - $44,000 / year",
    popularPrograms: ["Information Technology & Cybersecurity", "Engineering & Mining", "Nursing & Public Health", "Accounting & Finance"],
    postStudyWork: "2 to 4 Years Subclass 485 Temporary Graduate Visa",
    flag: "🇦🇺",
  },
  {
    slug: "uk",
    name: "United Kingdom",
    code: "GB",
    headline: "Study in the United Kingdom",
    tagline: "1-Year Master's degrees, prestigious Russell Group universities, and the Graduate Route visa.",
    intakes: "Autumn (Sep/Oct), Winter/Spring (Jan/Feb)",
    avgTuition: "£13,000 - £26,000 / year",
    popularPrograms: ["MBA & Management", "Data Science & Artificial Intelligence", "Biomedical Sciences", "Commercial Law"],
    postStudyWork: "2 Years Graduate Route Post-Study Work Visa",
    flag: "🇬🇧",
  },
  {
    slug: "germany",
    name: "Germany",
    code: "DE",
    headline: "Study in Germany",
    tagline: "Tuition-free or low-cost higher education at public universities, APS certification, and an 18-month job search visa.",
    intakes: "Winter (October), Summer (April)",
    avgTuition: "€0 - €3,000 / semester (Semester ticket contribution only in public universities)",
    popularPrograms: ["Automotive & Mechanical Engineering", "Computer Science & IT", "Renewable Energy", "International Business"],
    postStudyWork: "18-Month Post-Study Job Seeker Residence Permit",
    flag: "🇩🇪",
  },
  {
    slug: "france",
    name: "France",
    code: "FR",
    headline: "Study in France",
    tagline: "World-renowned Grandes Écoles, 5-year post-study Schengen alumni visa, and subsidized student accommodation.",
    intakes: "Autumn (September), Spring (February)",
    avgTuition: "€3,000 - €16,000 / year",
    popularPrograms: ["Luxury Brand & Fashion Management", "Culinary Arts & Hospitality", "Aerospace & Engineering", "Data Analytics & MBA"],
    postStudyWork: "2 Years APS (Autorisation Provisoire de Séjour) / Alumni Visa",
    flag: "🇫🇷",
  },
  {
    slug: "ireland",
    name: "Ireland",
    code: "IE",
    headline: "Study in Ireland",
    tagline: "The European tech and pharmaceutical capital with a 2-year Third Level Graduate Scheme for Master's graduates.",
    intakes: "Autumn (September), Spring (January)",
    avgTuition: "€11,000 - €25,000 / year",
    popularPrograms: ["Cloud Computing & AI", "Pharmaceutical Sciences", "Fintech & Quantitative Finance", "Digital Marketing"],
    postStudyWork: "2 Years Third Level Graduate Scheme (Masters)",
    flag: "🇮🇪",
  },
  {
    slug: "usa",
    name: "United States",
    code: "US",
    headline: "Study in the USA",
    tagline: "Leading global universities, flexible curriculum, campus assistantships, and up to 36 months of STEM OPT.",
    intakes: "Fall (August/Sep), Spring (January)",
    avgTuition: "$20,000 - $45,000 / year",
    popularPrograms: ["Computer & Data Engineering", "MBA & Business Analytics", "Biotechnology", "Applied Economics"],
    postStudyWork: "12 Months OPT + 24 Months STEM Extension (Up to 36 Months)",
    flag: "🇺🇸",
  },
  {
    slug: "europe",
    name: "Europe (Schengen)",
    code: "EU",
    headline: "Study Across Europe",
    tagline: "Schengen mobility, English-taught bachelor's & master's degrees in Netherlands, Sweden, Poland, and Hungary.",
    intakes: "September & February",
    avgTuition: "€2,500 - €14,000 / year",
    popularPrograms: ["International Business", "Computer Engineering", "Environmental Sciences", "Public Policy"],
    postStudyWork: "12 to 18 Months Post-Study Search Permits (varies by member state)",
    flag: "🇪🇺",
  },
];

// Immigration Services
export const IMMIGRATION_SERVICES = [
  {
    slug: "pr",
    title: "Permanent Residency (PR)",
    shortDesc: "Strategic profile evaluation for Express Entry, Federal Skilled Worker (FSW), and Australian General Skilled Migration.",
    badge: "Direct Pathways",
    href: "/immigration/pr",
  },
  {
    slug: "pnp",
    title: "Provincial Nominee Programs (PNP)",
    shortDesc: "Targeted provincial stream selection for Ontario, British Columbia, Alberta, Saskatchewan, and Manitoba.",
    badge: "Provincial Nominations",
    href: "/immigration/pnp",
  },
  {
    slug: "visitor-visa",
    title: "Visitor & Tourist Visa",
    shortDesc: "Thorough documentation, travel purpose justification, financial proof, and ties-to-home-country affidavits.",
    badge: "Family & Tourism",
    href: "/visitor-visa",
  },
  {
    slug: "australia",
    title: "Australia Immigration",
    shortDesc: "Subclass 189, 190, 491 points-tested visas, skills assessment through VETASSESS, ACS, and TRA.",
    badge: "Points Tested",
    href: "/immigration/australia",
  },
  {
    slug: "canada",
    title: "Canada Immigration",
    shortDesc: "Comprehensive Express Entry profile management, Category-Based Selections, and Canadian Experience Class (CEC).",
    badge: "CRS Evaluation",
    href: "/immigration/canada",
  },
  {
    slug: "refused-cases",
    title: "Visa Refusal Case Assessment",
    shortDesc: "Thorough forensic review of GCMS notes, refusal grounds under statutory sections, and revised file restructuring.",
    badge: "Specialized Analysis",
    href: "/immigration/refused-cases",
  },
];

// Test Preparation Courses
export const TEST_PREPARATION_COURSES = [
  {
    slug: "ielts",
    title: "IELTS Coaching",
    headline: "IELTS Academic & General Coaching in Patiala",
    shortDesc: "Personalized module coaching for Listening, Reading, Writing, and Speaking with daily exam simulations.",
    badge: "Academic & General",
    href: "/ielts",
  },
  {
    slug: "pte",
    title: "PTE Academic Prep",
    headline: "PTE Academic Lab Training in Patiala",
    shortDesc: "AI-scored computer lab practice, repeat sentence strategies, template mastery, and mock tests with real-time analytics.",
    badge: "AI Scoring Lab",
    href: "/pte",
  },
  {
    slug: "celpip",
    title: "CELPIP Training",
    headline: "CELPIP General Coaching for Canadian PR",
    shortDesc: "100% computer-delivered test coaching tailored for Canadian immigration Express Entry and citizenship requirements.",
    badge: "Canada PR Focused",
    href: "/test-preparation/celpip",
  },
  {
    slug: "cael",
    title: "CAEL Preparation",
    headline: "CAEL Test Coaching for Canadian Universities",
    shortDesc: "Canadian Academic English Language assessment coaching mimicking university lecture and seminar scenarios.",
    badge: "Academic English",
    href: "/test-preparation/cael",
  },
  {
    slug: "gre",
    title: "GRE Coaching",
    headline: "GRE Verbal & Quantitative Coaching in Patiala",
    shortDesc: "Structured quantitative problem-solving and verbal reasoning modules for US & Canadian graduate admissions.",
    badge: "Graduate School",
    href: "/test-preparation/gre",
  },
  {
    slug: "duolingo",
    title: "Duolingo English Test (DET)",
    headline: "Duolingo English Test Preparation",
    shortDesc: "Adaptive computer-based test preparation accepted by 4,000+ international universities and colleges.",
    badge: "Fast Results",
    href: "/test-preparation/duolingo",
  },
];

// Foreign Language Courses
export const LANGUAGE_COURSES = [
  {
    slug: "french",
    title: "French Language Training",
    levels: "A1 • A2 • B1 • B2",
    shortDesc: "DELF/TEF/TCF exam preparation. Earn up to 50 additional CRS points for Canada PR and qualify for French universities.",
    badge: "DELF / TEF Canada",
    href: "/languages/french",
  },
  {
    slug: "german",
    title: "German Language Training",
    levels: "A1 • A2 • B1 • B2",
    shortDesc: "Goethe-Zertifikat preparation for tuition-free study in Germany, APS verification, and EU employment opportunities.",
    badge: "Goethe Exam Prep",
    href: "/languages/german",
  },
  {
    slug: "spoken-english",
    title: "Spoken English & Personality",
    levels: "Basic to Advanced Fluency",
    shortDesc: "Overcome hesitation, master conversational English, professional interview readiness, and public speaking confidence.",
    badge: "Fluency & Confidence",
    href: "/languages/spoken-english",
  },
];

// Backward compatibility alias for any existing files referencing COUNTRIES_LIST or SERVICES_LIST
export const COUNTRIES_LIST = STUDY_ABROAD_COUNTRIES;
export const SERVICES_LIST = [
  {
    slug: "study-visa",
    title: "Study Abroad",
    shortDesc: "Complete admissions and student visa processing for top globally ranked institutions.",
    icon: "GraduationCap",
    badge: "Most Popular",
  },
  {
    slug: "immigration",
    title: "Immigration & PR",
    shortDesc: "Strategic legal pathway planning for skilled permanent residency and provincial nominations.",
    icon: "FileCheck2",
    badge: "Expert Advisory",
  },
  {
    slug: "visitor-visa",
    title: "Visitor & Tourist Visa",
    shortDesc: "Comprehensive documentation and statement preparation for hassle-free tourist travel.",
    icon: "Plane",
    badge: "Quick Process",
  },
  {
    slug: "business-immigration",
    title: "Business & Investor Visa",
    shortDesc: "Investor programs, entrepreneur pathways, and international business relocation.",
    icon: "Briefcase",
    badge: "High Net Worth",
  },
  {
    slug: "ielts",
    title: "IELTS Coaching",
    shortDesc: "Certified IELTS Academic & General training with real exam practice and band guarantee modules.",
    icon: "BookOpen",
    badge: "In-House Training",
  },
  {
    slug: "pte",
    title: "PTE Academic Prep",
    shortDesc: "Computer-lab AI scoring practice, simulated sectional mocks, and targeted speaking clinics.",
    icon: "Languages",
    badge: "Lab Access",
  },
  {
    slug: "language-courses",
    title: "Foreign Languages (French / German)",
    shortDesc: "A1 to B2 level certified foreign language batches for European university admissions & PR points.",
    icon: "Award",
    badge: "Certified Faculty",
  },
];
